### ISSUE TITLE
SE 등 작은 디바이스 대응 위한 View 레이아웃 등 재조정

### ISSUE THREAD

**Issue by dev-muuu** [Todoary/Todoary-iOS#447]
## 💡 issue
SE 등 작은 디바이스 대응 위한 View 레이아웃 등 재조정

## 📝 todo
- [x] 상단 기준 설정
- [x] 바텀시트 높이 
- [x] 약관 동의
- [x] 회원가입 > 간격 자체를 SE 버전으로 만들어달라고 부탁
- [x] 암호
- [x] 카테고리 추가/수정 바텀시트
